### ISSUE TITLE
homestead 下完全不能使用

### ISSUE THREAD

**Issue by jksusu** [ha-ni-cc/hyperf-watch#1]
环境  ubuntu homestead
hyperf 版本 1.0

启动什么的都是正常。但是日志报错

 ================================ 
 🚀 Start @ 2019-10-08 16:33:41
 ================================ 

Scanning ...
Scan completed.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Di\Listener\BootApplicationListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Config\Listener\RegisterPropertyHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Paginator\Listener\PageResolverListener listener.
[2019-10-08 16:33:47 @13188.0]	WARNING	swSocket_bind(:434): bind(0.0.0.0:9501) failed, Error: Address already in use[98]

In Server.php line 169:
                                                                               
  failed to listen server port[0.0.0.0:9501], Error: Address already in use[9  
  8]                                                                           
                                                                               

start

换一个端口，报错一个。

**Comment by ha-ni-cc** [comment]
shell版本的homestead没试过，建议使用PHP版本的watch试试
