### ISSUE TITLE
试了编，头两次改变文件会自动重启，然后多几次就不会自动重启了

### ISSUE THREAD

**Issue by zhangweixi** [ha-ni-cc/hyperf-watch#11]

**Comment by zhangweixi** [comment]
PHP Warning:  Swoole\Event::add(): already exist in /www/swoole/hyperf-skeleton/watch on line 109
发现定时器已经停止工作了

**Comment by ha-ni-cc** [comment]
请提供下您用的是什么系统？php版本和swoole版本？
php -v
php --ri swoole

**Comment by ha-ni-cc** [comment]
已更新解决这个问题。
