### ISSUE TITLE
hf 更新后失效

### ISSUE THREAD

**Issue by sevendiscovery** [ha-ni-cc/hyperf-watch#12]
更新了最新的hf版本
多次修改代码以后提示这个，然后导致服务直接无法响应
Warning: Swoole\Event::add(): already exist in /var/www/bravo-encode-api/watch.php on line 114

**Comment by ha-ni-cc** [comment]
更新的时候 watching？
还是更新后 再执行php watch报的错？

**Comment by ha-ni-cc** [comment]
已更新解决此问题。
