### ISSUE TITLE
swoole版本为4.5.1 使用失效

### ISSUE THREAD

**Issue by zsboss** [ha-ni-cc/hyperf-watch#14]
监听更新的时候，就会失效，

![image](https://user-images.githubusercontent.com/19493235/81772958-d0eaef00-9519-11ea-9cbb-02d542f9f4d3.png)

**Comment by ha-ni-cc** [comment]
感谢反馈，已更新解决。

**Comment by zsboss** [comment]
辛苦了，大佬
