### ISSUE TITLE
Windows 的下载不了

### ISSUE THREAD

**Issue by awkuan** [ha-ni-cc/hyperf-watch#15]
无法访问此网站找不到 raw.githubusercontent.com 的服务器 IP 地址。
尝试运行 Windows 网络诊断。
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ha-ni-cc** [comment]
应该是你的网络问题，换个网络重试下，最近你懂的，或挂个全局的科学上网。
或者你直接克隆整个仓库试试。

**Comment by s-proj** [comment]
> 应该是你的网络问题，换个网络重试下，最近你懂的，或挂个全局的科学上网。
> 或者你直接克隆整个仓库试试。

作者能弄个gitee的地址么 我的shell有wget这个watch现在啥网络都不好使了

**Comment by ha-ni-cc** [comment]
好的 等有空去建个仓库。

**Comment by ha-ni-cc** [comment]
> > 应该是你的网络问题，换个网络重试下，最近你懂的，或挂个全局的科学上网。
> > 或者你直接克隆整个仓库试试。
> 
> 作者能弄个gitee的地址么 我的shell有wget这个watch现在啥网络都不好使了

好的。Gitee仓库已建，地址：https://gitee.com/hanicc/hyperf-watch
