### ISSUE TITLE
修改文件几次后，重启服务就卡主不动，控制台没有信息输出，然后报warning错误

### ISSUE THREAD

**Issue by drttcrh** [ha-ni-cc/hyperf-watch#16]
[root@localhost api]# php watch -c
?? Start @ 2020-06-11 06:54:06
?? Watching 78 files...
rm -rf ./runtime/container/proxy
..
Detected an available cache, skip the app scan process.
Detected an available cache, skip the vendor scan process.
[INFO] Worker#1 started.
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9501
[INFO] Worker#2 started.
[INFO] Worker#3 started.
[INFO] Process[queue.default.0] start.
?? Restart @ 2020-06-11 06:54:31
?? Watching 78 files...
rm -rf ./runtime/container/proxy
..
Scanning app ...
Scan app completed, took 1277.706861496 milliseconds.
Detected an available cache, skip the vendor scan process.
[INFO] Worker#1 started.
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9501
[INFO] Worker#2 started.
[INFO] Worker#3 started.
[INFO] Process[queue.default.0] start.
?? Restart @ 2020-06-11 06:54:39
PHP Warning:  Swoole\Event::add(): already exist in xxx/api/watch on line 67
?? Watching 78 files...
rm -rf ./runtime/container/proxy
..
Scanning app ...
Scan app completed, took 1277.7030467987 milliseconds.
Detected an available cache, skip the vendor scan process.
[INFO] Worker#1 started.
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9501
[INFO] Worker#2 started.
[INFO] Worker#3 started.
[INFO] Process[queue.default.0] start.
[NOTICE] 
TIME:2020-06-11 02:55:11
PERMS:sys:user:list
IP:192.168.33.1
?? Restart @ 2020-06-11 06:55:11
PHP Warning:  Swoole\Event::add(): already exist in xxx/watch on line 67
?? Watching 78 files...

**Comment by ha-ni-cc** [comment]
该问题已修复，你重新下载watch覆盖。
