### ISSUE TITLE
hyperf 自带 cs-fix 建议可以在 reload 一定次数后进行编码格式修复

### ISSUE THREAD

**Issue by StringKe** [ha-ni-cc/hyperf-watch#18]

**Comment by ha-ni-cc** [comment]
没看明白标题的描述，欢迎PR！你指的是reload一定次数后，这个怎么限定？编码格式修复指的是哪一部分？监听的项目代码？

**Comment by StringKe** [comment]
你看 composer 的 scripts 里 有一个 cs-fix 的命令

reload 做一个计数器这种？比如说 5 次后进行代码格式化

**Comment by ha-ni-cc** [comment]
我认为这个不在热更新的主要工作范畴。关键是这个次数也不好确定，一般在自己push之前，自己执行下cs-fix即可。
