### ISSUE TITLE
俩个服务不能在一台机器同时运行，执行php watch -c 会把另外一个服务也会kill 掉 

### ISSUE THREAD

**Issue by Michael1994312** [ha-ni-cc/hyperf-watch#27]
测试环境和生产环境在一台机器上，生产环境用的 php bin/hyperf.php start，测试环境 php watch -c 如果后执行会把生产环境的服务也会kill掉，不太明白为啥，看watch脚本里的 killOldProcess 方法也是杀当前进程，希望作者解惑一下

**Comment by QiuCaYu** [comment]
它是先找pid去杀，找不到就直接匹配强杀进程：
这句执行的 ：$command
        = "ps -ef | grep '$match' | grep -v grep | awk '{print $2}' | xargs kill -9 2>&1";  
你的测试环境改下 APP_NAME，跟生产环境的不一样就不会被杀掉了。

**Comment by Michael1994312** [comment]
> 它是先找pid去杀，找不到就直接匹配强杀进程： 这句执行的 ：$command = "ps -ef | grep '$match' | grep -v grep | awk '{print $2}' | xargs kill -9 2>&1"; 你的测试环境改下 APP_NAME，跟生产环境的不一样就不会被杀掉了。

感谢回答，找到原因了，是因为watch文件的这句代码，list($name, $value) = explode('=', $val);解析.env文件没有去除空格，导致$_ENV数组的key都多了空格，所以获取$_ENV['APP_NAME']都是空的，就导致把.Master进程都杀掉了
