### ISSUE TITLE
【建议】默认日志级别的问题

### ISSUE THREAD

**Issue by yu1ec** [ha-ni-cc/hyperf-watch#3]
建议：
将log_level的级别调至SWOOLE_LOG_INFO或者以上。

场景：
我编译的swoole，是开启了debug和trace输出的，在执行大佬你的watch命令时，打印了一堆trace日志，我觉得，这种日志，我一个使用者应该没必要看到吧？

**Comment by ha-ni-cc** [comment]
你好，这个没试过呢，打印了一堆trace日志可以详细贴下图或者代码吗？或欢迎提PR！

**Comment by ha-ni-cc** [comment]
Thanks！
