### ISSUE TITLE
热加载建议

### ISSUE THREAD

**Issue by mengdodo** [ha-ni-cc/hyperf-watch#5]
目前用起来挺方便的，就是遇到一个问题，如果我在修改blade模版，也会触发reload动作，然后我就得等待3秒等它完成reload,可以过滤掉自定义文件后缀的文件监控吗

**Comment by ha-ni-cc** [comment]
可以的，你可以打开watch，按需编辑：
```
# Watch Ext 监听扩展名（多个可用英文逗号隔开）
const WATCH_EXT = 'php,env';
# Exclude Dir 排除目录（不监听的目录，数组形式)
const EXCLUDE_DIR = ['vendor'];
```
你可以排除掉blade模版的所在目录
比如你的view目录是：/storage/view
那么修改如下：
```
# Exclude Dir 排除目录（不监听的目录，数组形式)
const EXCLUDE_DIR = ['vendor', 'storage/view'];
```

**Comment by mengdodo** [comment]
@ha-ni-cc good job !
这个watch文件我都没点开看，马虎了，建议你写到readme中
