### ISSUE TITLE
请问如果是手游端的热更新怎么处理？

### ISSUE THREAD

**Issue by rexleimo** [ha-ni-cc/hyperf-watch#7]

**Comment by ha-ni-cc** [comment]
手游端？手游客户端做热更新？还是......表示没理解你的意思。

**Comment by rexleimo** [comment]
服务端的，可是hyperf 里面的热启动 好像没有执行完运行中的进程，就直接重启了




| |
莫东
|
|
rainbowmorel@163.com
|
签名由网易邮箱大师定制
在2020年2月28日 17:46，hanicc<notifications@github.com> 写道：

手游端？手游客户端做热更新？还是......表示没理解你的意思。

**Comment by ha-ni-cc** [comment]
emmm，你是想要优雅热重启吧？Hyperf跑在Docker里，利用Docker容器实现优雅热重启，但是像ws这种长连接还是会断一下。

**Comment by rexleimo** [comment]
只要之前的连接处理完的话就可以了，保证数据不出错。断一下无所谓，


| |
莫东
|
|
rainbowmorel@163.com
|
签名由网易邮箱大师定制
在2020年2月28日 17:55，hanicc<notifications@github.com> 写道：

emmm，你是想要优雅热重启吧？Hyperf跑在Docker里，利用Docker容器实现优雅热重启，但是连接还是会断一下。
