### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by nick2550123097** [ha-ni-cc/hyperf-watch#8]
➜  hyperf-skeleton php watch
🚀 Start @ 2020-02-26 13:40:16
📡 Watching 35 files...

Notice: Use of undefined constant SWOOLE_HOOK_ALL - assumed 'SWOOLE_HOOK_ALL' in /Users/nick/document/code/www/myself/hyperf/hyperf-skeleton/bin/hyperf.php on line 11
Scanning app ...

Fatal error: Declaration of App\Listener\DbQueryExecutedListener::process(App\Listener\object $event) must be compatible with Hyperf\Event\Contract\ListenerInterface::process(Hyperf\Event\Contract\object $event) in /Users/nick/document/code/www/myself/hyperf/hyperf-skeleton/app/Listener/DbQueryExecutedListener.php on line 27

**Comment by ha-ni-cc** [comment]
这个是Hyperf的启动报错，不是脚本导致的。看报错信息，先排查下swoole扩展版本，然后再排查框架的问题
