### ISSUE TITLE
CPU使用率过高

### ISSUE THREAD

**Issue by jqcool** [ha-ni-cc/hyperf-watch#9]
cup的使用率一直占用30%，导致电脑容易发热，建议优化下，比入适当的加些休眠时间

**Comment by ha-ni-cc** [comment]
脚本设定扫描时间默认间隔为2S，我这边MBP2015 CPU占用为0.1~0.2%

你的电脑CPU占用高是不是IO等待引起的？磁盘是HDD还是SSD，或者提供些有帮助的截图信息参考下

**Comment by taobali32** [comment]
> 脚本设定扫描时间预设间隔为2S，我这边MBP2015 CPU占用为0.1〜0.2％
> 
> 您的电脑CPU占用高是不是IO等待引起的？磁盘是HDD还是SSD，或者提供些有帮助的截图信息参考下

配置使用的是默认的，在macpro2019 docker 中 改变代码hou后非常消耗cpu

尝试设定扫描时间预设间隔为4s,还是不行

改变一次需要等待10秒+,是docker问题还是，如何可以稍微优化下

![image](https://user-images.githubusercontent.com/30717763/106550103-6ff2c380-654d-11eb-8604-5b4aa9782c69.png)
